api_platform:
    title: "Gestion de projet"
    version: "1.0.0"

    formats:
        jsonld:
            mime_types: ["application/ld+json"]
        json:
            mime_types: ["application/json"]

    swagger:
        swagger_ui_extra_configuration:
            docExpansion: none

    defaults:
        stateless: true
        pagination_enabled: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    mapping:
        paths:
            [
                "%kernel.project_dir%/src/Entity",
                "%kernel.project_dir%/src/ApiResource",
            ]

    eager_loading:
        enabled: true
        fetch_partial: false
        max_joins: 60 # ← augmente la limite (30 par défaut)
        force_eager: true # comportement par défaut

    enable_docs: true
    enable_entrypoint: true
