api_platform:
    title: Hello API Platform
    version: 1.0.0
    swagger:
        swagger_ui_extra_configuration:
            docExpansion: none
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    mapping:
        paths:
            [
                "%kernel.project_dir%/src/Entity",
                "%kernel.project_dir%/src/ApiResource",
            ]

    eager_loading:
        enabled: true
        fetch_partial: false
        max_joins: 60 # ← augmente la limite (30 par défaut)
        force_eager: true # comportement par défaut

